(setq inhibit-startup-message t)
(set-scroll-bar-mode nil)
(set-default-font "Menlo-14") 
(tool-bar-mode -1)
(setq make-backup-files nil)
(use-package maxframe
:ensure t
:config
(add-hook 'window-setup-hook 'maximize-frame t))
(fset 'yes-or-no-p 'y-or-n-p)
(global-set-key (kbd "<f5>") 'revert-buffer)
(defun my-comment-or-uncomment-region (beg end &optional arg)    
  (interactive (if (use-region-p)    
                   (list (region-beginning) (region-end) nil)    
                 (list (line-beginning-position)    
                       (line-beginning-position 2))))    
  (comment-or-uncomment-region beg end arg)    
)    
(global-set-key [remap comment-or-uncomment-region] 'my-comment-or-uncomment-region)
(global-set-key (kbd "C-c C-/") 'comment-or-uncomment-region)
(provide 'init-tweaks)
